.MODEL SMALL ; MEMORY MODEL SMALL
.STACK 100H ; STACK SIZE =100H 
.DATA
 N1 DW 0ABCDH ; 16-BIT HEX NUMBER 1 DIVIDEND 
 N2 DB 0BDH ; 8-BIT HEX NUMBER 2 DIVISOR 
 QUOT DB 00H ; QUOTIENT 
 REM DB 00H ; REMAINDER 
.CODE
 MAIN PROC
 MOV AX,@DATA
 MOV DS,AX ; INITIALIZE DATA SEGMENT 
 MOV AX,N1 ; MOVE N1 TO AX - DIVIDEND 
 MOV BL,N2 ; MOVE N2 TO BL - DIVISOR
 DIV BL ; AL=AX/BL AH=Remainder
 
 MOV QUOT,AL ; MOVE QUOTIENT TO MEMORY 
 MOV REM,AH ; MOVE REMAINDER TO MEMORY 
 MOV AH,4CH
 INT 21H
 MAIN ENDP
END MAIN
